version: '3'
services:
  fastApi-app:
      image: emptyvessel/fastApi-app:latest
      environment:
        - MONGODB_URL=mongodb://mongodb.lyftzeigen.ru:28017/randomTest
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - "8081:8081"
      networks:
        - shared-network

networks:
  shared-network:
    external: true