version: '3'
services:
  fastapi-app:
      image: emptyvessel/fastapi-app:latest
      env:
        MONGODB_HOST: ${{ secrets.MONGODB_HOST }}
        MONGODB_PORT: ${{ secrets.MONGODB_PORT }}
        MONGODB_USER: ${{ secrets.MONGODB_USER }}
        MONGODB_PASS: ${{ secrets.MONGODB_PASS }}
        MONGODB_AUTH_DB: ${{ secrets.MONGODB_AUTH_DB }}
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - "8081:8081"
      networks:
        - shared-network

networks:
  shared-network:
    external: true
