version: '3'
services:
  fastapi-app:
      image: emptyvessel/fastapi-app:latest
      environment:
        - MONGODB_URL=mongodb://mongodb.lyftzeigen.ru:28017
        - MONGODB_USER=testUser
        - MONGODB_PASS=root1234
        - MONGODB_COLLECT=rnbDB
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - "8081:8081"
      networks:
        - shared-network

networks:
  shared-network:
    external: true
